on: [push]

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Nuclei
      run: |
        git clone https://github.com/projectdiscovery/nuclei.git
        cd nuclei/v2/cmd/nuclei
        go build
        mv nuclei /usr/local/bin/
        nuclei -update-templates
        
    - name: Run Nuclei Scans
      run: |
        nuclei -target http://localhost:8080
